# Generated by Django 4.2.7 on 2023-11-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datavalue',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='datavalue',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
